[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "pyls"
version = "0.1.0"
description = "A Python implementation of the ls command"
requires-python = ">=3.6"

[project.scripts]
pyls = "pyls:main"